[global/wm]
margin-bottom = 0
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
width = 100%
height = 30
offset-x = 0
offset-y = 0
background = ${color.bg}
foreground = ${color.fg}
radius-top = 0.0
radius-bottom = 0.0
padding = 3
module-margin-left = 3
module-margin-right = 3

font-0 = "Droid Sans:size=9:weight=bold;3"
font-1 = "Iosevka Nerd Font:size=12;3"

modules-left = i3
modules-center = date
modules-right = xkeyboard memory network

separator =
dim-value = 1.0
wm-name =
locale =
enable-ipc = true
click-left =
click-middle =
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click =
cursor-scroll =

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Application Settings

[settings]
pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Colors

[color]
bg = #80000000
fg = #EAEAEA
fg-alt = #9C9C9C
trans = #00000000
white = #FFFFFF
black = #000000
red = #e53935
pink = #d81b60
purple = #8e24aa
deep-purple = #5e35b1
indigo = #3949ab
blue = #1e88e5
light-blue = #039be5
cyan = #00acc1
teal = #00897b
green = #43a047
light-green = #7cb342
lime = #c0ca33
yellow = #fdd835
amber = #ffb300
orange = #fb8c00
deep-orange = #f4511e
brown = #6d4c41
grey = #757575
blue-gray = #546e7a

theme-dark = #171831
theme-dark-brown = #2F1F2A
theme-dark-siren = #957095
theme-bezh = #C3A7BB
theme-siren = #9D9DCB
theme-pink = #F9D7CD

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
label-mode = %mode:🔒%
label-mode-padding = 1
label-focused = %index%
label-focused-background = ${color.theme-dark}
label-focused-foreground = ${color.theme-pink}
label-unfocused = %index%
label-visible = %index%
label-visible-background = ${color.fg-alt}
label-visible-foreground = ${color.bg}
label-urgent = %index%
label-urgent-background = ${color.theme-bezh}

pin-workspaces = true

label-focused-padding = 4
label-unfocused-padding = 4
label-visible-padding = 4
label-urgent-padding = 4

[module/date]
type = internal/date
interval = 1.0
time = "%d/%m/%Y %H:%M"
format = <label>
label = %time%

[module/memory]
type = internal/memory
interval = 2
format-prefix-foreground = ${color.fg-alt}
label = "%{T2}  %{T-}%gb_used%"

[module/network]
type = internal/network
interface = enp3s0
interval = 3.0
accumulate-stats = true
unknown-as-up = true
format-connected = <label-connected>
label-connected = "%{T2}󰈁 %{T-}%local_ip%"
format-disconnected = <label-disconnected>
label-disconnected = "%{T2}󰈂 %{T-}Нет сети"
label-disconnected-foreground = ${color.fg-alt}

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock

format = <label-layout>
format-spacing = 0

label-layout = %layout%
label-layout-padding = 1
label-layout-foreground = #fff
